language: python
python:
- '2.7'
sudo: false
branches:
  only:
  - master
before_install:
- chmod 755 ./.deploy-output.sh
- chmod 755 ./.multipage-split.sh
- nvm install 5.11.1
install:
- pip install pygments cssselect html5lib lxml
- git clone --depth=100 --branch=master https://github.com/tabatkins/bikeshed.git ./bikeshed
# Use stable copy of bikeshed
#- pushd ./bikeshed
#- git checkout 08075e7d3a9fd232f3ab09b4fe8f7b22abfe1345
#- popd
- pip install --editable ./bikeshed
- bikeshed update
# Use cached copy of bikeshed data files to give consistent builds
#- cp -R .spec-data/* ./bikeshed/bikeshed/spec-data
script: 'bikeshed spec && ./.multipage-split.sh'
after_success:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && ./.deploy-output.sh'
env:
  global:
    secure: f8K3ajqFaolqhZCK/SHL/0R9yXPT4b5aUBDle9sC95AdKyYqZRrPrg87QZo3FiyGCA1X6yIlkX9QNMa0Bo1GUO8tOVlh2Yz4aw+XfZ12fPAqHwiFkb38VCwUx3U3v5Nk3fyySKqnrbdfkL+oL98V6c7f0HS6udXAgTnI2QolT7Lj0NT5tAFou5FGGCqZt4/HU4LZllS8rM/YpzzKdv9A0GrZf2trNDQN+1ANGNqrLzgg8Xx5XIA6sRsG/gmXlTziYP2Wj13IRmfy/iQTRsbNfPbQD6S1pyRQOT9ILFicJNTqw3E+I4ila4aMpzxaVa9M8KQlcgAAIucAutsMYTyyfrKOGVOzqx886en1P+mCAaYEceiGHzBB0WuKkejrsUjap7sXZeIwViTMzpBKkRdldstvJdd+QP/l5t7dHEp9Gw2+r1xCFmkTfAqLyQNd9nxUcMTkFSJ2BZbDojDXq6IIhREmJJvB5hPqw4Z4EsyZ9KinN4Ffo4M7RoImg5IAPRY44VZywo2KgWpW77KE8pdPwhT8XxY7ME7Q6FB8PDfP1P7qHbGFchHk53sGXJJrQp4XCDEBUB2Hj+kYBLRb7mdrKdjqIFj/mr9E8Nap7pWckvOzR0prk2M60t8wixnfo3mE6H+xxJsK4VyKYFkVg601jV46q5T3SqW+r3DKEPTdzgk=
